services:
  - type: pserv
    name: lemon-rabbitmq
    env: docker
    dockerImage: rabbitmq:3-management
    plan: standard
    
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        value: hoyer
      - key: RABBITMQ_DEFAULT_PASS
        value: paglemonhoyer

    healthCheck:
      port: 15672
      path: /api/aliveness-test/
      initialDelaySeconds: 30
