services:
  - type: pserv
    name: lemon-rabbitmq
    env: docker
    dockerImage: rabbitmq:3-management
    plan: standard
    
    ports:
      - port: 5672
        protocol: TCP
      - port: 15672
        protocol: TCP

    healthCheck:
      port: 15672
      path: /api/aliveness-test/
